### ISSUE TITLE
can you make vencord version of these plugins 

### ISSUE THREAD

**Issue by Pickymarker** [philhk/better-discord-screenshare-plugin#19]
can you make vencord version of these plugins https://github.com/Tharki-God/BetterDiscordPlugins/blob/master/DiscordBypasses.plugin.js https://github.com/riolubruh/SplitLargeFiles and the custom camera quality from this plugin because without it discord caps camera to 720p  https://github.com/riolubruh/YABDP4Nitro

**Comment by philhk** [comment]
I might make a plugin in the future that lets you customize your camera :). And if you want to make plugin requests, please do so in the original [repo](https://github.com/Vendicated/Vencord) and not my fork. [SplitLargeFiles](https://github.com/Vendicated/Vencord/pull/800) is already being ported to Vencord to my knowledge, but I don't know if it will be accepted. And if you want to report any issues for my plugins (BetterScreenshare or BetterMicrophone) it would be great if you just comment [here](https://github.com/Vendicated/Vencord/pull/730). I also saw that you opened an issue earlier and if you still need help, just ask on the official [Vencord Discord](https://discord.gg/vencord).

**Comment by philhk** [comment]
I have news for you. I was trying to create a plugin to customize your camera but issue is Discord actually has a resolution limit of 720p. I can't say 100% that it's server-side, but the chance of it being server-side is really really high. You can still adjust the framerate and bitrate, but that seems a bit useless if you can't change the resolution. I also tested [YABDP4Nitro](https://github.com/riolubruh/YABDP4Nitro) and it has the same problem that anything over 720p is downscaled to 720p. You'll see the resolution you set on your client in your preview, but everyone else won't. You can also check it yourself like this:

![image](https://user-images.githubusercontent.com/66958695/231908751-be25373e-26e1-4b73-8ff4-0b2d2c19bdd0.png)
![image](https://user-images.githubusercontent.com/66958695/231908836-0eb34b8c-734d-4bdd-a52d-3d36f2a49eba.png)

**Comment by ThaUnknown** [comment]
afaik camera is also hardcoded on desktop, like screenshare is hardcoded on web as I've mentioned [here](https://github.com/Vendicated/Vencord/pull/730#issuecomment-1496324399)
