### ISSUE TITLE
The code is just Licenses

### ISSUE THREAD

**Issue by Jaie55** [philhk/better-discord-screenshare-plugin#21]

**Comment by philhk** [comment]
I'm aware that the code isn't that great, but firstly this is my code and this is what it looks like and secondly did you really just opened an issue to tell me my code is shit? Suggestions for improving my code are always welcome, but what you did was just completely unnecessary. I also started this as a side project and didn't really bother at first, and do you even know how hard it is to figure out how all these things work? I never thought I'd get hate for something like this, but I think it can happen on Github too. And the most hilarious thing about all this is that you are not even criticizing my code, but the compiled and minified code that comes from building the plugin (the one in the releases tab) 😂. If you want to look at the real code [this](https://github.com/philhk/better-discord-screenshare-plugin/tree/main/src) is it.

**Comment by jupelost** [comment]
Lmao what an asshole ignore him I appreciate you for this plug-in it has been one of the best features I believe should just be shipped with vanilla discord tbh you’re a lifesaver and a goat On Apr 28, 2023, at 2:06 PM, Phil ***@***.***> wrote:﻿
I'm aware that the code isn't that great, but firstly this is my code and this is what it looks like and secondly did you really just opened an issue to tell me my code is shit? Suggestions for improving my code are always welcome, but what you did was just completely unnecessary. I also started this as a side project and didn't really bother at first, and do you even know how hard it is to figure out how all these things work? I never thought I'd get hate for something like this, but I think it can happen on Github too. And the most hilarious thing about all this is that you are not even criticizing my code, but the compiled and minified code that comes from building the plugin (the one in the releases tab) 😂. If you want to look at the real code this is it.

**Comment by philhk** [comment]
I am very happy that you like it! Sadly there will always be people like
him :/.

Am Fr., 28. Apr. 2023 um 20:41 Uhr schrieb jupelost <
***@***.***>:

**Comment by Jaie55** [comment]
I didn't say that i don't like it, the thing is that i can not understand the code because is just 9000000 lines of LICENSES, so thats it. I apologize about that, anyways, is there any way to make it wokrs in Vencord, i did compile the Vencord fork, but i don't know how to install it

**Comment by philhk** [comment]
First of all you need to install [git](https://git-scm.com/) and [NodeJS](https://nodejs.org/en/download). After that open a PowerShell as administrator and type in
