### ISSUE TITLE
Streaming region

### ISSUE THREAD

**Issue by rlnt** [philhk/better-discord-screenshare-plugin#3]
Would it be possible to have a feature where only a portion of your monitor is streamed?
Eg when you have a 21:9 monitor but you only want to stream the left 16:9 part of it.

**Comment by philhk** [comment]
I will put this on the todo list. I'm pretty sure this wouldn't be possible, but maybe there is a way. The weird thing is that setting the capturing resolution should do exactly what you're saying, but it doesn't. Instead, the aspect ratio of the monitor is kept and then the image gets scaled down or up depending on the resolution you set. I'm closing this issue for now thanks for the suggestion!

**Comment by DAmNRelentless** [comment]
A weird way of handling issues but alright 😅
Yea, I also thought it would crop the image when setting the resolution scale manually but that sadly didn't work out.

I thought about creating a dummy window that is blank and still shows what's behind it so you can stream that instead but that would a very ugly implementation I think.

**Comment by philhk** [comment]
Is it 😂? I don't really know how to deal with issues on Github because I rarely get any. Thinking about it, I think it would be smarter to leave the issue open until a fix is found.
